sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t walkib/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true walkib/docker-react npm run test